package projectActivities;

import org.testng.Reporter;
import static io.restassured.RestAssured.given;

import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import io.restassured.builder.RequestSpecBuilder;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import io.restassured.specification.RequestSpecification;
import io.restassured.specification.ResponseSpecification;

public class ProjectTest {
	RequestSpecification requestSpec;
	ResponseSpecification responseSpec;
	String sshKey;
    int sshKeyId;
    @BeforeClass
    public void setUp() {
        sshKey = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC04J6qP3os7VMylFQXhyeURKrYPLY9SICWEUJZ8N+nrO2PC2MypB0Ffhu9zDO0GSABFgRDjCLixGaTfZmG6KJUoIbD7W+n6U2txd0ccIxeWtXu4GI0afnRmit0Mee0q2MTTJJ/Fh6cWx5Nd1AHgOQFtHK0ePBqpMjyLh9rmNvTE3Tw4QYHxV5VXErzk9qRK5IesXvhJBGwaUXKLPsmod4byY1WgxrxxB1bfjC4VFhGCZGVpIDCPjv4Bf2aCPzmGHlls0C3xVP3VmqYS2lDCscQYQKeBBZlkmtZYmIhCkt+NjpxkPoSP3z4x5j3ec6HegoI75i3F2qhNUBf0ThNiyLD Generated by ShowDNS - 2026-01-13"; 

        // Use RequestSpecBuilder to create the specification
        requestSpec = new RequestSpecBuilder()
            .setContentType(ContentType.JSON) // Set Content type to JSON
            .addHeader("Authorization", "token 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") 
            .setBaseUri("https://api.github.com") 
            .build();
    }
    @Test(priority = 1)
    public void postRequestTest() {
        String reqBody = "{\n" +
                "    \"title\": \"TestAPIKey\",\n" +
                "    \"key\": \"" + sshKey + "\"\n" +
                "}";

        Response response = given().spec(requestSpec)
                .body(reqBody)
                .when().post("/user/keys");

        String body = response.getBody().asPrettyString();
        Reporter.log("Post Response: " + body);

        sshKeyId = response.then().extract().path("id");

        response.then().statusCode(201);
    }

    @Test(priority = 2)
    public void getRequestTest() {
        Response response = given().spec(requestSpec)
                .pathParam("keyId", sshKeyId) // Use the extracted ID
                .when().get("/user/keys/{keyId}");

        Reporter.log("Get Response: " + response.asPrettyString());

        response.then().statusCode(200);
    }

    @Test(priority = 3)
    public void deleteRequestTest() {
        Response response = given().spec(requestSpec)
                .pathParam("keyId", sshKeyId)
                .when().delete("/user/keys/{keyId}");

        Reporter.log("Delete Response status code: " + response.getStatusCode());

        response.then().statusCode(204);
    }

  
}
